name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5.0.0
    - name: set up JDK 21
      uses: actions/setup-java@v5.0.0
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Detekt Check
      run: ./gradlew detekt
    - name: ktLink Check
      run: ./gradlew ktlintCheck
    - name: Build with Gradle
      run: ./gradlew build
